### ISSUE TITLE
Fazer os primeiros passos do front-end 

### ISSUE THREAD

**Issue by daminellis** [daminellis/plataforma_recrutamento_engeplus#1]
# morona 

- [x] Escolher quais frameworks serão usados e conferir se sao rentaveis ao projeto
- [x] Fazer os mockups do projeto

**Comment by M0rona** [comment]
No front end utilizaremos o Next Js, pois precisamos de um framework que utilize o SSR, pois as páginas serão indexadas no google, para acesso de candidatos.
Como biblioteca de estilos utilizaremos o tailwind, pela sua facilidade, juntamente com suas cores e tamanhos padronizados.
E como biblioteca de componentes utilizaremos o radix, personalizando-o com nossa necessidade.

**Comment by M0rona** [comment]
Finalizado o figma para o projeto:
[Link do figma](https://www.figma.com/design/LZ578KKeR8TDL7o4Q92o1h/%F0%9F%A7%91%E2%80%8D%F0%9F%92%BC-Plataforma-de-Recrutamento---Engeplus?node-id=15-2192&t=idOyl9Uo2JpVoesZ-1)
