### ISSUE TITLE
Desenhar o banco de dados e começar as escrituras 

### ISSUE THREAD

**Issue by daminellis** [daminellis/plataforma_recrutamento_engeplus#2]
- [x]  Desenhar o banco de dados no [dbdiagram.io](https://dbdiagram.io/)
- [x]  Comecar a escrever o que o time esta fazendo ao decorrer da semana e se tudo está correndo bem
- [x]  Conferir apos o banco escrito para evitar fazer mudanças depois de começar o back-end

**Comment by Lorrust** [comment]
# Modelagem

Iniciada modelagem do banco de dados, de acordo com modelo de negócio do projeto e especificações da documentação.

A modelagem ainda está incompleta e sofrerá alterações, entretanto está em andamento.

![Engeplus drawio (1)](https://github.com/user-attachments/assets/37884bea-6893-4484-9271-ad44016ba84d)

# Tecnologia

Assim como definido na documentação, o banco será desenvolvido no sistema de gerenciamento de banco de dados relacional MySQL.

Futuras modificações e iterações do banco de dados serão anunciadas aqui.
