### ISSUE TITLE
Definir as bases de segurança que serão usadas e criar back-end

### ISSUE THREAD

**Issue by daminellis** [daminellis/plataforma_recrutamento_engeplus#3]
- [x]  Verificar se todos os softwares escolhidos nao sao sucetiveis a falhas de segurança
- [x]  Escolher qual sera o back-end que será utiliado no projeto

**Comment by Guichardx2** [comment]
## Estrutura back-end do projeto: ##

### API: ###
Será adotada a linguagem TypeScript apoiada sobre a plataforma Node.js. O framework Nest.js foi escolhido como base para a construção da API, combinado com o framework web Fastify para otimizar o desempenho.  O Nest.js proporcionará uma estrutura modular e organizada, facilitando a criação de APIs escaláveis e sólidas. Já o Fastify, com sua alta performance, garantirá tempos de resposta rápidos e um baixo consumo de recursos nas requisições HTTP. 

Essa combinação permite que a aplicação entregue um desempenho superior em comparação a frameworks como o Express, tornando-a ideal para projetos que exigem alta concorrência e baixo tempo de resposta.

<hr/>

### Banco de dados: ###
Para estabelecer uma comunicação eficiente e segura com o banco de dados, optamos pelo TypeORM. Essa ferramenta, que atua como uma ponte entre os objetos do nosso código e as tabelas do banco, oferece recursos como mapeamento objeto-relacional, criação de migrações, suporte a diversos bancos de dados e tipagem forte.

Com o TypeORM, podemos realizar operações CRUD (Create, Read, Update, Delete) de forma intuitiva e segura, além de construir consultas complexas de maneira eficiente. Além disso, possui suporte e segurança na migração de dados e linguagem para outros bancos.

**Comment by Guichardx2** [comment]
## Segurança: ##

### TypeORM: ###
Será utilizado como ORM, garantindo a construção segura de queries SQL através de seus métodos de interpolação e Query Builder, prevenindo assim injeções SQL. As entidades do TypeORM serão configuradas com validações para garantir a integridade dos dados.

### Hashing de Senhas: ### 

As senhas dos usuários serão armazenadas de forma segura utilizando algoritmos de hashing como bcrypt ou Argon2, combinados com um salt único para cada senha, dificultando ataques de força bruta.

### Autenticação JWT: ### 

A autenticação dos usuários será realizada através de JSON Web Tokens (JWT), com a utilização de um Refresh Token para renovar os tokens sem expor a senha do usuário.

### Proteção de Rotas: ###

Apenas usuários autenticados terão acesso às funcionalidades da aplicação, garantindo que dados sensíveis não sejam expostos a usuários não autorizados.

### Controle de Acesso: ###
Será implementado um sistema de roles e permissions para definir os níveis de acesso de cada usuário aos diferentes recursos da aplicação.

### Comunicação Segura: ###

A comunicação entre o cliente e o servidor será protegida através de um certificado SSL, garantindo a confidencialidade e integridade dos dados transmitidos.

### CORS: ###

As configurações de CORS serão definidas de forma rigorosa para evitar ataques de cross-origin e permitir apenas as origens permitidas.

### Cookies: ###

Os cookies de sessão serão configurados com as flags Secure e HttpOnly para aumentar a segurança e dificultar ataques de sessão hijacking.

### Armazenamento de Sessões: ###

As informações da sessão serão armazenadas em um store de sessões seguro, protegido contra acessos não autorizados.

### Gerenciamento de Vulnerabilidades: ###

Ferramentas como Snyk ou Dependabot serão utilizadas para monitorar as dependências da aplicação e identificar vulnerabilidades, garantindo que as correções sejam aplicadas de forma rápida e eficiente.
