### ISSUE TITLE
Adicionando novas issues ao jean

### ISSUE THREAD

**Issue by daminellis** [daminellis/plataforma_recrutamento_engeplus#4]
- [x]  Começar a fazer os models do banco no backend
- [x]  Começar a fazer os comandos do backend 
- [x]  Verificar se todos os metodos de segurança sao suportados nas engines escolhidas

**Comment by Guichardx2** [comment]
Entities das tabelas do banco de dados criadas! Seguindo para a conexão com o banco, controllers, models e services.

**Comment by Guichardx2** [comment]
### Entidades e conexão feita. ###

Vou seguir o planejamento de Trello...
